// My Name: Dylan Harvey
// My Class: CPSC 1021
// Date: 1/22/2024
// Desc: 
// Time: 

#include <iostream>

using namespace std;

int main() {
    // DEFINE THE NAMED CONSTANT PI HERE AND SET ITS VALUE TO 3.14159

    // DECLARE ALL NEEDED VARIABLES HERE. GIVE EACH ONE A DESCRIPTIVE
    // NAME AND AN APPROPRIATE DATA TYPE.

    // WRITE STATEMENTS HERE TO DISPLAY THE 4 MENU CHOICES.

    // WRITE A STATEMENT HERE TO INPUT THE USER'S MENU CHOICE.

    // USE AN IF/ELSE IF STATEMENT TO OBTAIN ANY NEEDED INPUT INFORMATION
    // AND COMPUTE AND DISPLAY THE AREA FOR EACH VALID MENU CHOICE.
    // ASSUME THE USER ENTERS VALID METRICS, E.G. DOESN’T ENTER
    // A STRING OR NEGATIVE NUMBER.
    // IF AN INVALID MENU CHOICE WAS ENTERED, AN ERROR MESSAGE SHOULD
    // BE DISPLAYED.

    return 0;
}